---
- name: Deploy Streaming App
  hosts: aws-streamers
  become: true
  tasks: 
    - name: Gather ip
      shell: curl -s 'https://api.ipify.org'
      register: ip_result
    - name: Log into DockerHub
      docker_login:
        registry_url: ghcr.io
        username: mcottontensor
        password: "{{ gh_api_key }}"
    - name: Remove existing streamer container
      docker_container:
        name: psstreaming_project_1
        state: absent
    - name: Remove existing signaling container
      docker_container:
        name: psstreaming_signalling_1
        state: absent
    # - name: Remove existing coturn container
    #   docker_container:
    #     name: psstreaming_coturn_1
    #     state: absent
    - name: Start container with GPUs
      community.docker.docker_compose:
        project_name: psstreaming
        definition:
          version: '2'
          services:
            # AWS ubuntu seems to already have a turn server running
            # turnserver:
            #   image: "coturn/coturn:4.5.2"
            #   init: true
            #   network_mode: "host"
            #   command: ["-a", "-v", "-n", "-u", "user:password", "-p", "3478", "-r", "default-realm", "--no-dtls", "--no-tls"]
            
            signalling:
              image: "{{ signalling_image_url }}"
              init: true
              network_mode: "host"
              command:
                - "--publicIp={{ ip_result.stdout }}"
                - >-
                  --peerConnectionOptions={
                      "iceServers":[
                        {
                          "urls": ["stun:stun.l.google.com:19302"]
                        },
                        {
                          "urls": ["turn:{{ ip_result.stdout }}:3478"],
                          "username": "user",
                          "credential": "password"
                        }
                      ]
                    }
              # depends_on:
              #   - turnserver
            
            project:
              image: "{{ app_image_url }}"
              network_mode: "host"
              command: ["-RenderOffscreen", "-Windowed", "-ForceRes", "-ResX=1920", "-ResY=1080", "-PixelStreamingIP=127.0.0.1", "-PixelStreamingPort=8888"]
              
              depends_on:
                - signalling
              
              deploy:
                resources:
                  reservations:
                    devices:
                    - driver: nvidia
                      capabilities: [gpu]
                      count: 1
