name: Deploy Test App

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Test App Docker Image"]
    types:
      - completed

jobs:
  deploy:
    permissions: write-all
    runs-on: [ubuntu-latest]
    environment: main
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: "Checkout GitHub Action - TestApp"
        uses: actions/checkout@v3
        with:
          clean: "false"
      - name: Run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: 'BuildTools/'
          playbook: 'deploy_playbook.yml'
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          key: ${{secrets.DEPLOY_SSH_PRIVATE_KEY}}
          inventory: ${{secrets.DEPLOY_INVENTORY}}
          options: |
            -u ubuntu
            -e @secrets.enc
            --extra-vars "ue_version=${{ env.UE_VERSION }}"
