name: Deploy Test App

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Test App Docker Image"]
    types:
      - completed

env:
  DEPLOY_SIGNALLING_URL: "mcottontensor/ps_test_signalling:5.0"
  DEPLOY_APP_URL: "mcottontensor/pstesting:5.0-Shipping"

jobs:
  deploy:
    permissions: write-all
    runs-on: [ubuntu-latest]
    environment: main
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: "Checkout GitHub Action - TestApp"
        uses: actions/checkout@v3
        with:
          clean: "false"
      - name: Run deploy playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: 'BuildTools/'
          playbook: 'deploy_playbook.yml'
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          inventory: ${{ vars.DEPLOY_INVENTORY }}
          options: |
            -u ubuntu
            --extra-vars "gh_api_key=${{ secrets.GH_API_KEY }} app_image_url=${{ env.DEPLOY_APP_URL }} signalling_image_url=${{ env.DEPLOY_SIGNALLING_URL }}"
