name: Build Test App Docker Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Package Test App"]
    types:
      - completed

jobs:
  package:
    permissions: write-all
    runs-on: [ubuntu-latest]
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
     - name: "Checkout GitHub Action - TestApp"
        uses: actions/checkout@v3
        with:
          clean: "false"
      - name: Download Latest Release
        id: download
        uses: robinraju/release-downloader@v1.8
        with: 
          filename: "*"
          latest: true
          tarBall: true
          zipBall: false
      - name: Extract files
        uses: a7ul/tar-action@v1.1.0
        id: extract
        with:
          command: x
          cwd: ./extract
          files: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: sourcedir=./extract/Linux
          push: true
          tags: mcottontensor/pstesting:latest
