name: Build and Release Test App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  package:
    permissions: write-all
    runs-on: [self-hosted, aws, Linux]
    environment: main
    env:
      OUT_PATH: "${{ github.workspace }}/../Output"
    steps:
      - name: "Checkout GitHub Action - TestApp"
        uses: actions/checkout@v3
        with:
          clean: "false"
      - name: "Remove existing artifacts"
        run: |
          rm -rf ${{ env.OUT_PATH }}
      - name: Read the project version
        id: getversion
        run: |
          echo "version=$(awk -F '=' '/ProjectVersion/ {print $2}' Config/DefaultGame.ini)" >> $GITHUB_OUTPUT
      - name: "Build TestApp ${{ vars.BUILD_CONFIG }}"
        run: >
          ${{ vars.UE_PATH }}/Engine/Build/BatchFiles/RunUAT.sh
          BuildCookRun
          -project="${{ github.workspace }}/TestApp.uproject"
          -build
          -cook
          -stage
          -archive
          -archivedirectory="${{ env.OUT_PATH }}/${{ vars.BUILD_CONFIG }}"
          -package
          -pak
          -targetplatform=Linux
          -target=TestApp
          -clientconfig=${{ vars.BUILD_CONFIG }}
          -nodebuginfo
          -nop4
      - name: Archive ${{ vars.BUILD_CONFIG }} build
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: '${{ env.OUT_PATH }}/${{ vars.BUILD_CONFIG }}'
          files: |
            Linux
          outPath: '${{ env.OUT_PATH }}/${{ steps.getversion.outputs.version }}-${{ github.ref_name }}-${{ github.event.repository.name }}-Linux.tar.gz'
      - name: "Make the release"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.getversion.outputs.version }}-${{ github.ref_name }}-${{ github.event.repository.name }}"
          artifacts: "${{ env.OUT_PATH }}/${{ steps.getversion.outputs.version }}-${{ github.ref_name }}-${{ github.event.repository.name }}-Linux.tar.gz"
          generateReleaseNotes: true
          allowUpdates: true
